version : '3'

services:
  nodejs:
    image: kstrckr/franconite-js
    container_name: franconite_vue
    restart: unless-stopped
    networks:
      - app-network

  webserver:
    image: nginx:mainline-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - web-root:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - dhparam:/etc/ssl/certs
    depends_on:
      - nodejs
    networks:
      - app-network

  certbot_com:
    image: certbot/certbot
    container_name: certbot_com
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - webserver
    command: certonly --webroot --webroot-path=/var/www/html --email kurt@kurtstrecker.io --agree-tos --no-eff-email --force-renewal -d kurtstrecker.com  -d www.kurtstrecker.com


  certbot_io:
    image: certbot/certbot
    container_name: certbot_io
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - webserver
    command: certonly --webroot --webroot-path=/var/www/html --email kurt@kurtstrecker.io --agree-tos --no-eff-email --force-renewal -d kurtstrecker.io  -d www.kurtstrecker.io


volumes:
  certbot-etc:
  certbot-var:
  web-root:
    driver: local
    driver_opts:
      type: none
      device: /var/www/html
      o: bind
  dhparam:
    driver: local
    driver_opts:
      type: none
      device: /home/franc/dhparam/
      o: bind
networks:
  app-network:
    driver: bridge
